### ISSUE TITLE
Flamegraph / Pyroscope prototype

### ISSUE THREAD

**Issue by janpaul123** [Zaplib/zaplib#177]
Checklist copy-pasted from my recent livestream

# Goals
* [ ] Publish Pyroscope case study
  * [ ] Implement Zaplib flamegraph in Pyroscope open source project (JP)
  * [ ] Benchmark Zaplib implementation against existing implementation (Steve)

# Tasks
Not fun:
* [ ] Text rendering looks bad on non-retina screen
* [ ] Fix spaces in example_text
* [ ] Fix rect border / coordinates

Rote:
* [ ] "Focus rectangle" highlighting
* [ ] Temporarily disable scrolling / panning

Fun:
* [ ] Head first vs tail first
    * [ ] No ellipsis at all
    * [ ] Cut off letters or not?
* [ ] Integration into Pyroscope
    * [ ] Hello world integration (toolchain, tests, etc)
    * [ ] Rendering at proper location
    * [ ] Transfer data
    * [ ] Popover when hovering (keep in DOM)
    * [ ] Highlighting when selecting item in the side table
    * [ ] Search highlighting
    * [ ] Focus subtree
* [ ] Better font

Future improvements:
* [ ] Bring back scrolling / panning
    * [ ] Fix scrolling behavior when zoomed in a lot
    * [ ] Scrolling around current mouse position
* [ ] Ellipsis glyph
    * [ ] Figure out why it doesn't render currently
